### ISSUE TITLE
Question: fakekmscon initrd text mode (cage + foot)

### ISSUE THREAD

**Issue by VannTen** [n3rdopolis/fakekmscon#2]
Hello o/
In https://old.reddit.com/r/linux/comments/10eccv9/config_vtn_in_2023/ you allude to using a cage + foot combo for replacing VT if initrd fails somehow.

Do you know if it's possible to use the same process for the normal text mode verbose boot process (not using plymouth), while using a systemd based initrd ? I assume it would be similar somehow to what you have in recinit :thinking:

**Comment by n3rdopolis** [comment]
Not as good as plymouth. In theory it could be possible I guess, maybe just run `dmesg`, but plymouth also reads from /dev/console when booting (if plymouthd has --mode=boot), not just /dev/kmsg so `dmesg` would to miss the logging that systemd does. Also it would probably need a systemd service that kills cage
